user_config:
  user_name: mhenkel
  key_path: /home/mhenkel/.ssh/id_rsa.pub
  base_directory: /var/lib/libvirt/images
networks:
  access1:
    network_type:
      subnet: 10.0.0.0/24
  core1:
    network_type:
      subnet: 10.0.1.0/24
  core2:
    network_type:
      subnet: 10.0.2.0/24
  access2:
    network_type:
      subnet: 10.0.3.0/24
  mgmt:
    network_type:
      name: default
instances:
  host1:
    vcpu: 4
    memory: 4
    image: /var/lib/libvirt/images/mantic-server-cloudimg-amd64.img
  host2:
    vcpu: 4
    memory: 4
    image: /var/lib/libvirt/images/mantic-server-cloudimg-amd64.img
  router1:
    vcpu: 4
    memory: 4
    image: /var/lib/libvirt/images/mantic-server-cloudimg-amd64.img
  router2:
    vcpu: 4
    memory: 4
    image: /var/lib/libvirt/images/mantic-server-cloudimg-amd64.img
interfaces:
  host1_eth0:
    mtu: 2000
    network: mgmt
    instance: host1
    routes:
  host1_eth1:
    mtu: 2000
    network: access1
    instance: host1
    routes:
      access2:
        instance: router1
        interface: router1_eth1
  host2_eth0:
    mtu: 2000
    network: mgmt
    instance: host2
    routes:
  host2_eth1:
    mtu: 2000
    network: access1
    instance: host2
    routes:
      access1:
        instance: router1
        interface: router1_eth1
  router1_eth0:
    mtu: 2000
    network: mgmt
    instance: router1
    routes:
  router1_eth1:
    mtu: 2000
    network: access1
    instance: router1
    routes:
  router1_eth2:
    mtu: 2000
    network: core1
    instance: router1
    routes:
      access2:
        instance: router2
        interface: router2_eth2
  router1_eth3:
    mtu: 2000
    network: core2
    instance: router1
    routes:
      access2:
        instance: router2
        interface: router2_eth3
  router2_eth0:
    mtu: 2000
    network: mgmt
    instance: router2
    routes:
  router2_eth1:
    mtu: 2000
    network: access2
    instance: router2
    routes:
  router2_eth2:
    mtu: 2000
    network: core1
    instance: router2
    routes:
      access1:
        instance: router1
        interface: router1_eth2
  router2_eth3:
    mtu: 2000
    network: core2
    instance: router2
    routes:
      access1:
        instance: router1
        interface: router1_eth3
